# Generated by Django 4.0.6 on 2022-08-08 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleHistoru',
            new_name='SaleHistory',
        ),
        migrations.AlterField(
            model_name='card',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='store.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(to='store.meterial'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
